# data parameters
#dataset_name: imagenet
dataset_name: celeba-hq       
data_with_subfolder: False      # is the dataset located in subfolder?
all_data_path: sample_dataset/train   # train_data dir
gt_data_path: sample_dataset/gt   # gt_data dir
test_data_path: test_samples   # test dir

checkpoint_path: checkpoints
output_test_dir: output     # test results' save path
resume: checkpoints        # if not, leave this value blank
resume_iter: 100000          # if you use resume checkpoint, pick iter num
save_result_as_colored: True  # If true, test outputs are saved as colored image  (RGB)
                              # If not, the test outputs are saved as label number (0~15)

batch_size: 12    # training batch
test_batch: 1    # test batch

image_shape: [128, 128, 3]
random_crop: False    # for dataset image loading
# training parameters
cuda: True

gpu_ids: [1]    # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 1
lr: 0.0001
lr_decay: 0.95
momentum: 0.95
weight_decay: 0.0005
beta1: 0.5
beta2: 0.9
niter: 100000
print_iter: 100
viz_iter: 2500
snapshot_save_iter: 5000